### ISSUE TITLE
Template path must be updated in OAKoha.pl

### ISSUE THREAD

**Issue by kidclamp** [ebsco/openathens-koha-plugin#1]
Causing error 'bad template path'

The $PluginDir variable in OAKoha.pl should use the same code as the main module
Replace:
my $PluginDir = dirname(abs_path($0));                                                                  
With:
my $PluginDir = C4::Context->config("pluginsdir");                                                        
$PluginDir = $PluginDir.'/Koha/Plugin/OAKoha';

**Comment by minusdavid** [comment]
I think Cam has updated this but will leave it for someone else to check

**Comment by cambw** [comment]
Yes updated 👍
