### ISSUE TITLE
OAKoha.pl does not work with newer Koha vesions (tried 21.11)

### ISSUE THREAD

**Issue by jotkaka** [ebsco/openathens-koha-plugin#11]
Hi!

I'm not sure if the project is still active, but I find it very useful. The version for 17.11.xx worked well for 20.05.  Unfortunately not for 21.11.  At least two spots are to be corrected in OAKoha.pl -- functions have to be imported explicitly now:
```
use C4::Auth qw( get_template_and_user );
use C4::Output qw( output_html_with_http_headers );
```
Also, in line (ca.) 115 `eq` should be used instead of `==` (twice).

Janusz

**Comment by minusdavid** [comment]
I had to look at this just now, and it looks like those function exports are the bare minimum that are needed. 

I'm planning to do a pull request for this in about 16 hours.

**Comment by minusdavid** [comment]
I may have gotten impatient and just did it now: 

https://github.com/ebsco/openathens-koha-plugin/pull/12

**Comment by mkstephens** [comment]
We were just upgraded to 21.11.05 from 21.05 and are now having this issue as well. Please review the pull request and release an updated version of the plugin!

**Comment by mmabrahamson** [comment]
I've created a new version of the PR so that we can create a 21.11 branch and have an appropriate release created.  Can you test the KPZ here and let me know if it's working properly for you?  https://github.com/ebsco/openathens-koha-plugin/blob/Koha-21.11.x/oa_plugin_21.1101.kpz. I'm unable to test locally at the moment.

**Comment by kylemhall** [comment]
@mmabrahamson we are experiencing the same error, and I can verify your patched kpz works!

**Comment by mmabrahamson** [comment]
Thanks!  I'll go ahead and close this issue then.  I appreciate the confirmation!
