### ISSUE TITLE
Installing new version can be problematic

### ISSUE THREAD

**Issue by kidclamp** [ebsco/openathens-koha-plugin#2]
Can get repeating errors for installation if plugin has been installed before:

DBD::mysql::db do failed: Duplicate entry 'OA::Plugin-installedversion' for key 'PRIMARY' [for Statement "INSERT INTO plugin_data (plugin_class, plugin_key, plugin_value) VALUES ('OA::Plugin', 'installedversion', '16.1105')"] at /var/lib/koha/{instance}/plugins/Koha/Plugin/OAKoha.pm line 169.

changing the install lines as below cleared the error:
        my $pluginSQL = C4::Context->dbh->do("INSERT IGNORE INTO `plugin_data` (`plugin_class`, `plugin_key`, `plugin_value`) VALUES ('OA::Plugin', 'installedversion', '".$VERSION."')");
        $pluginSQL = C4::Context->dbh->do("UPDATE `plugin_data` SET `plugin_value` ='".$VERSION."'  WHERE `plugin_class` = 'OA::Plugin' AND `plugin_key`= 'installedversion'");

**Comment by minusdavid** [comment]
Oops I made a duplicate for this one... 

Another idea would be to remove this plugin data during uninstall of the plugin.

**Comment by cambw** [comment]
Fixed in latest patches
